// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsBnOB8rot8-5uUseBJAlrPnbhW-F4-TM',
    appId: '1:790200842377:web:d8ad21ccb69b32bbcbee58',
    messagingSenderId: '790200842377',
    projectId: 'smart-ms-6b6fd',
    authDomain: 'smart-ms-6b6fd.firebaseapp.com',
    storageBucket: 'smart-ms-6b6fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdJjlpDqwQsNZnW-NOGoRivMkvEEQtvSs',
    appId: '1:790200842377:android:39f5671632e10b15cbee58',
    messagingSenderId: '790200842377',
    projectId: 'smart-ms-6b6fd',
    storageBucket: 'smart-ms-6b6fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9pTdRwa-El_h0HwtprRpjclTM6uBdZfE',
    appId: '1:790200842377:ios:32b0901b1fe10ff1cbee58',
    messagingSenderId: '790200842377',
    projectId: 'smart-ms-6b6fd',
    storageBucket: 'smart-ms-6b6fd.appspot.com',
    iosBundleId: 'com.example.helloAisha1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9pTdRwa-El_h0HwtprRpjclTM6uBdZfE',
    appId: '1:790200842377:ios:ff296b0447d3b01ccbee58',
    messagingSenderId: '790200842377',
    projectId: 'smart-ms-6b6fd',
    storageBucket: 'smart-ms-6b6fd.appspot.com',
    iosBundleId: 'com.example.helloAisha1.RunnerTests',
  );
}
